# Generated by Django 4.2.1 on 2023-06-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='image',
            field=models.ImageField(default='/static/shop/img/dummy_300x300_ffffff_cccccc.png', upload_to='uploads/products/'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='has_basket',
            field=models.BooleanField(default=False),
        ),
    ]
